### ISSUE TITLE
Remove unused 2022 code

### ISSUE THREAD

**Issue by cal-miller-harvard** [BitBucketsFRC4183/FRC2023-Charged-Up#14]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/Robot.java#L110

Elsewhere also?

**Comment by cal-miller-harvard** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/Buttons.java#L31

More in Buttons.java

**Comment by cal-miller-harvard** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/utils/MathUtils.java#L7

This comment

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/auto-orient/src/main/java/frc/robot/utils/MathUtils.java#L39

And this one

**Comment by cal-miller-harvard** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/tree/auto-orient/src/main/java/frc/robot/config

Is this whole section unused 2022 code? You moved config to be per subsystem? Or maybe you want one global config file with limited stuff in it?

**Comment by vkedia05** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/commit/f3a05d79c97c9079793d99720190951adc400664

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/commit/38da39f60e7ceb7ef7fe1d7b981b0b2a288a53cd
