### ISSUE TITLE
Add triggers to xbox controller config class

### ISSUE THREAD

**Issue by cal-miller-harvard** [BitBucketsFRC4183/FRC2023-Charged-Up#15]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/Buttons.java#L19

should be here

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/auto-orient/src/main/java/frc/robot/utils/Xbox.java

**Comment by vkedia05** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/commit/7a09ab719005c2e6c72ccecfeb01513dbd7ac906
