### ISSUE TITLE
ArmControl.isErrorSmallEnough should use Math.abs

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2023-Charged-Up#150]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/main/src/main/java/org/bitbuckets/arm/ArmControl.java#L73-L75

To test it, remove this commented out test code:

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/main/src/test/java/org/bitbuckets/arm/ArmControlTest.java#L56-L60

**Comment by therbun** [comment]
already did and pushed changes
