### ISSUE TITLE
Arm PID is too fast

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2023-Charged-Up#153]
Our Arm moves too quickly. We should use motion profiling instead of standard positional pid to make it smoothly achieve position. We only need regular positional pid when tuning.

**Comment by cal-miller-harvard** [comment]
In addition, feedforward control based on the position/ velocity/ acceleration will make a big difference- I don’t know to what extent that’s already implemented, but I think 3467 has example code you can use.

**Comment by cpostbitbuckets** [comment]
For reference, here is an example project using DJArmFeedFoward: https://github.com/WHS-FRC-3467/Skip-5.13/blob/master/src/main/java/frc/robot/subsystems/arm/ArmSubsystem.java#L211-L239

Should be pretty easy to copy/paste it into our project to test it if our Motion Profile isn't good enough.
