### ISSUE TITLE
Delete old PID constants class (or Balance subsystem)

### ISSUE THREAD

**Issue by cal-miller-harvard** [BitBucketsFRC4183/FRC2023-Charged-Up#16]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/auto-orient/src/main/java/frc/robot/subsystem/balance/PID.java

**Comment by cal-miller-harvard** [comment]
Actually, should the whole balance subsystem be deleted? Is any of it still used?

**Comment by cal-miller-harvard** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/auto-orient/src/main/java/frc/robot/config/PID.java

Also delete this one

**Comment by vkedia05** [comment]
Deleted everything but to lazy to find commit
