### ISSUE TITLE
Minor drivetrain fixes

### ISSUE THREAD

**Issue by cal-miller-harvard** [BitBucketsFRC4183/FRC2023-Charged-Up#18]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/subsystem/drivetrain/DrivetrainSubsystem.java#L57
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/subsystem/drivetrain/DrivetrainSubsystem.java#L97
Move speed modifier to preferences and delete where it's set here

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/subsystem/drivetrain/DrivetrainSubsystem.java#L32
Delete or move irrelevant comments like this one

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/subsystem/drivetrain/DrivetrainSubsystem.java#L83
Delete

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/subsystem/drivetrain/DrivetrainSubsystem.java#L215
Consider moving a field oriented drive method here, instead of having it in default drive command - it could be useful elsewhere

**Comment by cal-miller-harvard** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/d10069b99e5cebe88510020f593d2f2ac9f6bf0a/src/main/java/frc/robot/commands/DefaultDriveCommand.java#L73

Change this to stop command

**Comment by vkedia05** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/commit/c19f3bfb248869176dd63d931caf00e978a79354

**Comment by vkedia05** [comment]
Did not do the field oriented stuff yet, I do not want to mess with it right now as it has been working. That can be something to consider once Matt pushes his swerve code which will change a lot

**Comment by cal-miller-harvard** [comment]
OK. Let’s move that into the drivetrain FSM project. One component of the state will be robot-oriented vs field oriented translation.
