### ISSUE TITLE
Re-enable and test odometry based on drivetrain kinematics

### ISSUE THREAD

**Issue by cal-miller-harvard** [BitBucketsFRC4183/FRC2023-Charged-Up#21]
https://docs.wpilib.org/en/stable/docs/software/kinematics-and-odometry/swerve-drive-odometry.html

Should display position on dashboard. Eventually, will integrate with vision pose estimation

**Comment by arcaputo** [comment]
I think order to use swerveodometry WPILib requires you to use kinematics, so I'll definitely implement this and add it to smartdashboard...or advantagescope? depending on what I'm supposed to be using

**Comment by superyuuki** [comment]
Advantagescope, but Mattlib automatically sends it to both

**Comment by superyuuki** [comment]
Simply use the Loggables

**Comment by arcaputo** [comment]
Gotcha, simply will use the loggables then

**Comment by cpostbitbuckets** [comment]
Odometry is great, can visualize on AdvantageScout
