### ISSUE TITLE
Minor balance fixes

### ISSUE THREAD

**Issue by cal-miller-harvard** [BitBucketsFRC4183/FRC2023-Charged-Up#22]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/commands/AutoBalanceCommand.java#L29

Refer to value in constants file instead of hard coding, here and elsewhere

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/f10fa1f23a7f888f68c0bb3e6e5e051ab9c35ed4/src/main/java/frc/robot/commands/AutoBalanceCommand.java#L42

Rename to BalanceDeadband_deg to match unit naming convention elsewhere. Also Roll_Deg -> Roll_deg

**Comment by vkedia05** [comment]
https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/commit/e72e068bd3c1d7bc4999c4bcade3c05dea4e325e
