### ISSUE TITLE
Integrate WPI preferences for our configurable values

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2023-Charged-Up#38]
We would like to be able to update PID constants using the smart dashboard while we were running our robot. It will make tuning pid faster.

**Comment by cal-miller-harvard** [comment]
@vkedia05 ’s auto balance/ drivetrain angle code had a reasonable implementation of this, which should be straightforward to port to the current codebase, unless @superyuuki wants to handle it differently.

**Comment by cal-miller-harvard** [comment]
This still needs to be done, but can be done with the new tunables.

**Comment by DanielWhatsGood** [comment]
Switched to tuneables; fixed
