### ISSUE TITLE
Switch to WPILib XboxController class

### ISSUE THREAD

**Issue by cal-miller-harvard** [BitBucketsFRC4183/FRC2023-Charged-Up#52]
https://first.wpi.edu/wpilib/allwpilib/docs/release/java/edu/wpi/first/wpilibj/XboxController.html

Remove https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/eee0986c44f3517b2f22df58ed47a136112fd999/src/main/java/org/bitbuckets/robot/XboxConstants.java

**Comment by superyuuki** [comment]
@DanielWhatsGood

**Comment by cpostbitbuckets** [comment]
Done by @vkedia05
