### ISSUE TITLE
Add SparkSetup

### ISSUE THREAD

**Issue by cal-miller-harvard** [BitBucketsFRC4183/FRC2023-Charged-Up#53]
Need a version of the current TalonSetup file for Spark Max motor controllers for 2023 drive and mechanisms

https://github.com/BitBucketsFRC4183/FRC2023-Charged-Up/blob/elevatorPrototype/src/main/java/org/bitbuckets/lib/vendor/ctre/TalonSetup.java

**Comment by superyuuki** [comment]
Did you look in vendor/spark

**Comment by cal-miller-harvard** [comment]
I didn't see this, but was looking at the wrong branch of the code. Consider renaming to vendor/rev. Should this be closed or are there still necessary features to add?

**Comment by superyuuki** [comment]
Limit switches, followers, are the only features missing

Smartmotion is also missing but not specified in my IMotorController contract

**Comment by cal-miller-harvard** [comment]
Sounds good, I'll leave the issue open for now.

Perhaps we should add another ISmartMotorController interface that implements SmartMotion/ Motion Magic
