### ISSUE TITLE
Easy enable/mock of control classes

### ISSUE THREAD

**Issue by cpostbitbuckets** [BitBucketsFRC4183/FRC2023-Charged-Up#90]
We are going to have to turn on and off various parts of our robot for testing. We should make this as convenient for students as possible.

At the top of RobotSetup.java we should have something like:

```java
boolean driveEnabled = true;
boolean armEnabled = true;
boolean elevatorEnabled = true;
```

then in our actual setup, if that is false, return a mock control. If it's true, return the real one. This way a student can easily see what's enabled on their robot and they can easily toggle them on/off while testing.

**Comment by DanielWhatsGood** [comment]
Has this been fixed yet? If not, I'll start working on this right away

**Comment by cpostbitbuckets** [comment]
This is good
